# ============================================================
# Phase 4 Migration Script - Package Skeleton & Mechanical Move
# Run this from the repository root (where app.py currently lives).
# Safe to review before running - every operation is a directory
# creation, a whole-file/folder move, or a brand-new file write.
# Nothing here edits the content of an existing file - that's Part 2.
# ============================================================

if (-not (Test-Path ".\app.py")) {
    Write-Error "app.py not found in the current directory. Run this script from the repository root."
    exit 1
}

Write-Host "Creating directory structure..." -ForegroundColor Cyan

New-Item -ItemType Directory -Force -Path ".\drafts" | Out-Null
New-Item -ItemType Directory -Force -Path ".\data" | Out-Null
New-Item -ItemType Directory -Force -Path ".\scripts" | Out-Null
New-Item -ItemType Directory -Force -Path ".\src\topo_astro\core" | Out-Null
New-Item -ItemType Directory -Force -Path ".\src\topo_astro\techniques\primary_directions" | Out-Null
New-Item -ItemType Directory -Force -Path ".\src\topo_astro\batch" | Out-Null
New-Item -ItemType Directory -Force -Path ".\src\topo_astro\persistence" | Out-Null
New-Item -ItemType Directory -Force -Path ".\src\topo_astro\webapp\reserve" | Out-Null

Write-Host "Creating __init__.py package markers with brief docstrings..." -ForegroundColor Cyan

'"""topo_astro - the Topocentric Astro rectification application, as an installable package."""' | Set-Content -Encoding UTF8 -Path ".\src\topo_astro\__init__.py"
'"""core - pure domain calculation layer (constants, aspect matching). No knowledge of Flask or batch orchestration."""' | Set-Content -Encoding UTF8 -Path ".\src\topo_astro\core\__init__.py"
'"""techniques - the seven calculation techniques (Primary Directions, Secondary, PSSR, Transit, SRA, Harmonics, Lunar)."""' | Set-Content -Encoding UTF8 -Path ".\src\topo_astro\techniques\__init__.py"
'"""techniques.primary_directions - the Primary Directions technique, split into trig.py (spherical-trig core) and technique.py (orchestration)."""' | Set-Content -Encoding UTF8 -Path ".\src\topo_astro\techniques\primary_directions\__init__.py"
'"""batch - the offline/batch rectification engine and orchestration entry points ("Mode 2" per the Developer Manual)."""' | Set-Content -Encoding UTF8 -Path ".\src\topo_astro\batch\__init__.py"
'"""persistence - reading and writing saved_selections/*.txt files."""' | Set-Content -Encoding UTF8 -Path ".\src\topo_astro\persistence\__init__.py"
'"""webapp - the interactive Flask application ("Mode 1" per the Developer Manual)."""' | Set-Content -Encoding UTF8 -Path ".\src\topo_astro\webapp\__init__.py"
'"""webapp.reserve - preserved, currently-unwired web-layer utilities and the reserved kerykeion charting work (once Phase 8 relocates it)."""' | Set-Content -Encoding UTF8 -Path ".\src\topo_astro\webapp\reserve\__init__.py"

Write-Host "Moving whole files to their new homes (renames noted in comments)..." -ForegroundColor Cyan

# core/
Move-Item -Force ".\constants.py"          ".\src\topo_astro\core\constants.py"
Move-Item -Force ".\aspects_base.py"       ".\src\topo_astro\core\aspects.py"                              # renamed

# techniques/
Move-Item -Force ".\pd_base.py"            ".\src\topo_astro\techniques\primary_directions\trig.py"        # renamed
Move-Item -Force ".\pd_automate.py"        ".\src\topo_astro\techniques\primary_directions\technique.py"   # renamed
Move-Item -Force ".\secondary_automate.py" ".\src\topo_astro\techniques\secondary_progressions.py"         # renamed
Move-Item -Force ".\pssr_swiss_auto.py"    ".\src\topo_astro\techniques\pssr.py"                            # renamed
Move-Item -Force ".\transit_swiss_auto.py" ".\src\topo_astro\techniques\transits.py"                        # renamed
Move-Item -Force ".\sra_auto.py"           ".\src\topo_astro\techniques\sra.py"                             # renamed
Move-Item -Force ".\harmonics_auto.py"     ".\src\topo_astro\techniques\harmonics.py"                       # renamed
Move-Item -Force ".\lunar_auto.py"         ".\src\topo_astro\techniques\lunars.py"                          # renamed

# batch/
Move-Item -Force ".\main_techniques.py"          ".\src\topo_astro\batch\entrypoints.py"                   # renamed
Move-Item -Force ".\process_techniques_files.py" ".\src\topo_astro\batch\grid_engine.py"                   # renamed
Move-Item -Force ".\csv_analysis.py"             ".\src\topo_astro\batch\analysis.py"                      # renamed

# webapp/
Move-Item -Force ".\app.py"    ".\src\topo_astro\webapp\app.py"
Move-Item -Force ".\templates" ".\src\topo_astro\webapp\templates"
Move-Item -Force ".\static"    ".\src\topo_astro\webapp\static"

# drafts/ (moved unmodified - do not edit this file, see drafts/README.md)
Move-Item -Force ".\pd_assist.py" ".\drafts\pd_assist.py"

# data/ (format unchanged, just relocated)
Move-Item -Force ".\data_input"       ".\data\data_input"
Move-Item -Force ".\data_rect"        ".\data\data_rect"
Move-Item -Force ".\data_times"       ".\data\data_times"
Move-Item -Force ".\saved_selections" ".\data\saved_selections"

Write-Host "Creating drafts/README.md..." -ForegroundColor Cyan

@'
# drafts/

This directory holds incomplete, non-executing sketches kept as a
reference or starting point for future work - not part of the
installable `src/topo_astro` package, and not expected to import cleanly
or run.

## pd_assist.py

Ends mid-statement (`jd_mature = jd_rad +`) and cannot be parsed as valid
Python. Appears to be working toward an arc-derived "maturity date"
calculation between two planets. Kept exactly as it was in the original
codebase, unmodified - reconstructing its intent is a design/feature
decision, not a mechanical migration step, so it isn't attempted here.
'@ | Set-Content -Encoding UTF8 -Path ".\drafts\README.md"

Write-Host "Creating core/reserve.py (calc_alt, calc_lst, add_suffix_to_tuples)..." -ForegroundColor Cyan

@'
"""
core/reserve.py - preserved, currently-unwired general-purpose astronomy
utilities, relocated out of the primary-directions technique module they
used to live in (pd_automate.py) since they aren't PD-specific.

None of these have a current caller anywhere in the application. They are
kept, not deleted, because they represent real, working formulas that
would be costly to reconstruct if a future feature needs them (e.g.
calc_alt/calc_lst for a visibility/rise-set feature, or if the reserved
kerykeion charting work in webapp/reserve/ is ever revisited).
"""
import math
import swisseph as swe


def add_suffix_to_tuples(tuples_list, suffix):
    return tuple(list(t) + [suffix] for t in tuples_list)


def calc_alt(lst_hours, ra_deg, decl_deg, latitude_deg):
    """
    Calculate the altitude of an astronomical object given LST, RA, Dec, and Latitude.

    Parameters:
    lst_str (str): Local Sidereal Time in HH:MM:SS format.
    ra_deg (float): Right Ascension in degrees.
    dec_deg (float): Declination in degrees.
    latitude_deg (float): Latitude of the observer in degrees.

    Returns:
    float: Altitude in degrees.
    """    
    lst_deg = lst_hours * 15.0
    h = lst_deg - ra_deg
    h = swe.degnorm(h)    #normalize degree

    lat_rad = math.radians(latitude_deg)
    decl_rad = math.radians(decl_deg)
    h_rad = math.radians(h)

    alt_rad = math.asin(math.sin(decl_rad) * math.sin(lat_rad) + 
                        math.cos(decl_rad) * math.cos(lat_rad) * math.cos(h_rad))

    alt_deg = math.degrees(alt_rad)

    return alt_deg


def calc_lst(jd, longitude):
    """
    Calculate the Local Sidereal Time (LST) and Greenwich Mean Sidereal Time (GMST)
    from Julian Date (JD) and longitude.

    Parameters:
    jd (float): Julian Date.
    longitude (float): Longitude of the location in degrees.

    Prints:
    - Julian Date
    - Greenwich Mean Sidereal Time
    - Local Sidereal Time
    """

    # Convert longitude to degrees, minutes, seconds format for display
    hemisphere = 'E' if longitude > 0 else 'W'
    longitude_deg = int(abs(longitude))
    longitude_min = int((abs(longitude) - longitude_deg) * 60)
    longitude_sec = int(((abs(longitude) - longitude_deg) * 60 - longitude_min) * 60)

    # Calculate Greenwich Mean Sidereal Time (GMST)
    gmst = 18.697374558 + 24.06570982441908 * (jd - 2451545)
    gmst = gmst % 24  # Convert to 24-hour format

    # Convert longitude to sidereal hours
    longitude_hours = longitude / 15.0

    # Calculate Local Sidereal Time (LST)
    lst = gmst + longitude_hours
    if lst < 0:
        lst += 24
    elif lst >= 24:
        lst -= 24
    
    return lst
'@ | Set-Content -Encoding UTF8 -Path ".\src\topo_astro\core\reserve.py"

Write-Host "Creating techniques/primary_directions/reserve.py (get_directed_from_data)..." -ForegroundColor Cyan

@'
"""
techniques/primary_directions/reserve.py - a preserved, currently-unwired
alternate Primary Directions calculation path.

get_directed_from_data implements the same MD > SA quadrant-shift
correction as PD_Base.set_directed_data (trig.py), but takes already-
computed intermediate values (GEO_LAT, DECL, RA, RAMC, mc, house_pos, ac,
long, e) directly as parameters, rather than deriving them internally
from a radix/event pair on every call. Not currently wired into
PD_Automate's active call path - kept because it's a genuinely different,
lower-level, composable entry point that could be useful for a future
caching/bulk-optimization pathway (e.g. reusing RA/DECL/RAMC across many
events for one radix without recomputing them from the ephemeris each
time), not a worse or older copy of the same thing.
"""
import swisseph as swe
from julian import from_jd

from .trig import (
    get_quadrant_from_house_pos,
    calc_md_to_oa_data,
    calc_left_right_angles,
    shift_point_to_closest_next_quad,
    calc_arc,
    calc_long_from_OA,
)


def get_directed_from_data(jd_radix, jd_event, GEO_LAT, DECL, RA, RAMC, mc, flag_direct, house_pos, ac, long, e):
    quadrant = get_quadrant_from_house_pos(house_pos)
    MD, _, SA, phi, _, OA_OD, FLAG_ASCEN = calc_md_to_oa_data(RA, RAMC, quadrant, GEO_LAT, DECL, ac, long)

    if (MD > SA):
        left_angle, right_angle = calc_left_right_angles(ac, mc, quadrant)
        new_quadrant = shift_point_to_closest_next_quad(long, left_angle, right_angle, quadrant)
        MD, _, SA, phi, _, OA_OD, FLAG_ASCEN = calc_md_to_oa_data(RA, RAMC, new_quadrant, GEO_LAT, DECL, ac, long)
        
        if (MD > SA):
            with open("log_md_sa.txt", "a") as file:
                    file.write(f"before \t{from_jd(jd_radix)} ra: {RA} md: {MD} sa: {SA} : oad {OA_OD} {FLAG_ASCEN} \n")

            new_quadrant = shift_point_to_closest_next_quad(long, left_angle, right_angle, quadrant)
            MD, _, SA, phi, _, OA_OD, FLAG_ASCEN = calc_md_to_oa_data(RA, RAMC, new_quadrant, GEO_LAT, DECL, ac, long)
            
            with open("log_md_sa.txt", "a") as file:
                    file.write(f"mid \t{from_jd(jd_radix)} md: {MD} sa: {SA} : oad {OA_OD} {FLAG_ASCEN} \n")

            if (MD > SA):
                with open("log_md_sa.txt", "a") as file:
                    file.write(f"last \t{from_jd(jd_radix)} md: {MD} sa: {SA} : oad {OA_OD} {FLAG_ASCEN} \n")

    arc = calc_arc(jd_radix, jd_event)
    dir_OA = OA_OD + arc if flag_direct else OA_OD - arc
    dir_OA = swe.degnorm(dir_OA)

    LONG_deg = calc_long_from_OA(dir_OA, phi, e, FLAG_ASCEN)
    '''print(f"arc: {arc}")
    print(f"directed OA/OD: {dir_OA}")
    print(f"long directed: {LONG_deg}")'''
    
    return LONG_deg
'@ | Set-Content -Encoding UTF8 -Path ".\src\topo_astro\techniques\primary_directions\reserve.py"

Write-Host "Creating webapp/reserve/timezone_name_lookup.py..." -ForegroundColor Cyan

@'
"""
webapp/reserve/timezone_name_lookup.py - a preserved, currently-unwired
web-layer utility.

get_timezone_name_from_pos returns an IANA timezone name (e.g.
"Europe/London") for a lat/long pair. It has no current caller - the one
place that used to call it, the /generate_chart route's kerykeion-based
SVG generation, currently has that call commented out (see
webapp/reserve/charting_kerykeion/ once Phase 8 relocates that code).
Kept because it's a complete, correct, working utility, not because it's
still wired into anything today.
"""
from timezonefinder import TimezoneFinder


def get_timezone_name_from_pos(geopos):
    tf = TimezoneFinder()
    geo_lat = geopos[0]
    geo_long = geopos[1]
    
    return tf.timezone_at(lat=geo_lat, lng=geo_long)
'@ | Set-Content -Encoding UTF8 -Path ".\src\topo_astro\webapp\reserve\timezone_name_lookup.py"

Write-Host "Creating webapp/reserve/clear_directory.py..." -ForegroundColor Cyan

@'
"""
webapp/reserve/clear_directory.py - a preserved, currently-unwired
web-layer utility.

clear_directory deletes and recreates a directory (e.g. for resetting a
charts/ or temp/ output folder before a batch regeneration). Zero current
callers anywhere in the application - kept because it's a small, complete,
working utility that a future feature (e.g. the reserved kerykeion
charting work) could plausibly need.
"""
import os
import shutil


def clear_directory(directory_path):
    if os.path.exists(directory_path) and os.path.isdir(directory_path):
        shutil.rmtree(directory_path)
        os.makedirs(directory_path)  # Recreate the empty directory
    else:
        print("Directory does not exist or is not a directory.")
'@ | Set-Content -Encoding UTF8 -Path ".\src\topo_astro\webapp\reserve\clear_directory.py"

Write-Host "Creating persistence/selections.py (parse_selection_file)..." -ForegroundColor Cyan

@'
"""
persistence/selections.py - the single canonical reader for
saved_selections/*.txt files.

parse_selection_file is used by both the interactive Flask app (to reload
a person's previously-saved aspect selections) and the batch Excel-export
path (create_analysis_workbook). There must be only one implementation of
this - app.py used to define its own, near-identical shadowing copy; that
was removed during the de-duplication phase (see the migration plan) in
favor of always importing this one.
"""
import os
import logging


def parse_selection_file(filepath):
    """Reads a saved selection file and parses it into a dictionary."""
    if not os.path.exists(filepath):
        logging.info(f"Selection file not found: {filepath}")
        return None

    loaded_selections = {}
    current_event = None
    current_technique = None
    line_number = 0

    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            for line_content in f:
                line_number += 1
                processed_line = line_content.rstrip()

                if not processed_line.startswith(' ') and processed_line.startswith("Event: "):
                    current_event = processed_line[len("Event: "):].strip()
                    if not current_event: # Handle empty event string if it occurs
                        logging.warning(f"Empty event string found at line {line_number} in {filepath}")
                        current_event = f"UNKNOWN_EVENT_{line_number}" # Placeholder
                    loaded_selections[current_event] = {}
                    current_technique = None
                elif processed_line.startswith("  ") and not processed_line.startswith("   ") and "Technique: " in processed_line:
                    if current_event:
                        try:
                            technique_part = processed_line.split("Technique: ", 1)[1]
                            current_technique = technique_part.strip()
                            if not current_technique: # Handle empty technique string
                                logging.warning(f"Empty technique string for event '{current_event}' at line {line_number} in {filepath}")
                                current_technique = f"UNKNOWN_TECHNIQUE_{line_number}" # Placeholder
                            loaded_selections[current_event][current_technique] = []
                        except IndexError:
                            logging.warning(f"Malformed Technique line for event '{current_event}' at line {line_number} in {filepath}: {processed_line}")
                            current_technique = None
                    else:
                        logging.warning(f"Found Technique line without preceding Event at line {line_number} in {filepath}: {processed_line}")
                        current_technique = None
                elif processed_line.startswith("    - "): # No need for 'not startswith("     ")' if structure is consistent
                    if current_event and current_technique:
                        # Ensure the technique key and list exist
                        if current_technique not in loaded_selections[current_event]:
                            logging.warning(f"Aspect found for event '{current_event}' but technique '{current_technique}' not initialized at line {line_number} in {filepath}. Initializing.")
                            loaded_selections[current_event][current_technique] = []

                        if isinstance(loaded_selections[current_event].get(current_technique), list):
                            aspect = processed_line[len("    - "):].strip()
                            if aspect: # Only add non-empty aspects
                                loaded_selections[current_event][current_technique].append(aspect)
                        else: # Should not happen if initialized correctly
                            logging.error(f"Critical parsing error: Technique list for '{current_event}' -> '{current_technique}' is not a list at line {line_number} in {filepath}.")
                    # else: Ignore aspect lines found out of proper context

        logging.info(f"Successfully parsed selections from {filepath}")
        # print("Parsed Dictionary:", loaded_selections) # Keep for debugging if needed
        return loaded_selections

    except Exception as e:
        logging.error(f"Error parsing selection file {filepath} at line ~{line_number}: {e}")
        return None
'@ | Set-Content -Encoding UTF8 -Path ".\src\topo_astro\persistence\selections.py"

Write-Host ""
Write-Host "Mechanical move complete." -ForegroundColor Green
Write-Host "Next: apply Part 2 (import updates + manual edits), Part 3 (Flask config - read first, no change is actually needed), and Part 4 (docstrings) before running anything." -ForegroundColor Yellow